"""empty message

Revision ID: c689a96ec28c
Revises: a9d949fb5c9d
Create Date: 2022-03-13 22:20:55.644451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c689a96ec28c'
down_revision = 'a9d949fb5c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fishes', sa.Column('vertical_length', sa.Float(), nullable=False))
    op.add_column('fishes', sa.Column('horizontal_length', sa.Float(), nullable=False))
    op.drop_column('fishes', 'length')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fishes', sa.Column('length', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('fishes', 'horizontal_length')
    op.drop_column('fishes', 'vertical_length')
    # ### end Alembic commands ###
