"""empty message

Revision ID: db416022b922
Revises: c689a96ec28c
Create Date: 2022-03-13 22:23:27.234134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db416022b922'
down_revision = 'c689a96ec28c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fishes', sa.Column('diagonal_length', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fishes', 'diagonal_length')
    # ### end Alembic commands ###
